# These are default configurations that will be used by default if they are not overridden by a Spring Profile or by e.g. a command-line argument.
# Profile-specific configurations can be defined in application-[profile].yml and will override these settings if they conflict.

logging:
  level:
    root: INFO
    web: INFO
    org.springframework: INFO
    net.joeclark.webapps.granite: INFO

spring:
  thymeleaf:
    cache: false
