# Settings for the 'dev' profile intended to be used on the developer's personal computer.
# These complement and override settings from 'application.yml'.

# Log everything!
logging:
  level:
    root: INFO
    org.springframework: DEBUG
    net.joeclark.webapps.granite: TRACE

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/granite
    username: granite
    password: test

