# These are default configurations that will be used by default if they are not overridden by a Spring Profile or by e.g. a command-line argument.
# Profile-specific configurations can be defined in application-[profile].yml and will override these settings if they conflict.

logging:
  level:
    root: WARN
    org.springframework: INFO
    net.joeclark: DEBUG

spring:
  thymeleaf:
    cache: false
  datasource:
    # Default datasource for local testing. Override in an environment-specific config file, e.g. application-prod.yaml
    # Some of our automated tests need at least the 'url' line to be here, even if the database doesn't actually exist.
    url: jdbc:postgresql://localhost:5432/granite
    username: granite
    password: test
