# Settings for testing when database and app are within a Docker bridge network.
# These complement and override settings from 'application.yml'.

logging:
  level:
    root: INFO
    org.springframework: DEBUG
    net.joeclark.webapps.granite: TRACE

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.0.1:5432/granite
    username: granite
    password: test
    initialization-mode: always

