# These are default configurations that will be used by default if they are not overridden by a Spring Profile or by e.g. a command-line argument.
# Profile-specific configurations can be defined in application-[profile].yml and will override these settings if they conflict.

logging:
  level:
    root: WARN
    org.springframework: INFO
    net.joeclark: DEBUG

spring:
  thymeleaf:
    cache: false
  datasource:
    # Default datasource for testing within a Docker network. Override in an environment-specific config file, e.g.
    # application-dev.yaml which uses 'localhost' as the host name, or an application-prod.yaml for your real database.
    # (NB: Some of our automated tests need the 'url' line to be here, even if the database doesn't actually exist.)
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.0.1:5432/granite
    username: granite
    password: test
    initialization-mode: always
