# Settings for the 'dev' profile intended to be used on the developer's personal computer.
# These complement and override settings from 'application.yml'.

# Log everything!
logging:
  level:
    web: TRACE
    net.joeclark.webapps.granite: TRACE
